import React from 'react';
import { Link } from 'react-router-dom';
import AbcDisplayComponent from '../../../components/AbcDisplayComponent';
import QuizComponent from '../../../components/QuizComponent';
import { Quiz } from '../../../types';

const gameQuiz: Quiz = {
    id: 'aos7-game-quiz',
    title: 'Video Game Music Level-Up Quiz',
    questions: [
        {
            id: 'gq1',
            text: 'What is "Adaptive Music" (or Dynamic Music) in a video game?',
            options: [
                { id: 'gq1a1', text: 'Music that stays the same no matter what happens' },
                { id: 'gq1a2', text: 'Music that changes its volume, layers, or sections based on player actions' },
                { id: 'gq1a3', text: 'Music that you can download as a ringtone' },
                { id: 'gq1a4', text: 'Music played on a piano' },
            ],
            correctAnswerId: 'gq1a2',
            explanation: 'Adaptive music reacts to the game state (e.g., entering combat, low health, or changing locations).'
        },
        {
            id: 'gq2',
            text: 'What is "Horizontal Re-sequencing"?',
            options: [
                { id: 'gq2a1', text: 'Stretching the music to make it longer' },
                { id: 'gq2a2', text: 'Switching from one musical section to another at a specific transition point' },
                { id: 'gq2a3', text: 'Playing the music upside down' },
                { id: 'gq2a4', text: 'Recording the music in a studio' },
            ],
            correctAnswerId: 'gq2a2',
            explanation: 'This involves jumping between different musical loops or segments based on the game\'s logic.'
        },
        {
            id: 'gq3',
            text: 'What is "Vertical Re-orchestration" (or Layering)?',
            options: [
                { id: 'gq3a1', text: 'Adding or removing instrumental tracks in real-time within the same piece' },
                { id: 'gq3a2', text: 'Turning the speakers up' },
                { id: 'gq3a3', text: 'Using only tall instruments like the double bass' },
                { id: 'gq3a4', text: 'Playing chords instead of melodies' },
            ],
            correctAnswerId: 'gq3a1',
            explanation: 'Layering allows the music to become "denser" (e.g., adding drums when an enemy appears) without breaking the flow.'
        },
        {
            id: 'gq4',
            text: 'Early game music was limited to "Chiptune". What does this mean?',
            options: [
                { id: 'gq4a1', text: 'Music played on a guitar' },
                { id: 'gq4a2', text: 'Music generated by the console\'s sound chip using simple waveforms (Square, Triangle, Noise)' },
                { id: 'gq4a3', text: 'Expensive orchestral music' },
                { id: 'gq4a4', text: 'Music with no rhythm' },
            ],
            correctAnswerId: 'gq4a2',
            explanation: 'Early hardware (like the NES) could only produce a few voices of synthesized sound simultaneously.'
        },
        {
            id: 'gq5',
            text: 'Who composed the iconic "Super Mario Bros." and "Zelda" themes?',
            options: [
                { id: 'gq5a1', text: 'Hans Zimmer' },
                { id: 'gq5a2', text: 'Koji Kondo' },
                { id: 'gq5a3', text: 'Nobuo Uematsu' },
                { id: 'gq5a4', text: 'John Williams' },
            ],
            correctAnswerId: 'gq5a2',
            explanation: 'Koji Kondo is the legendary composer behind Nintendo\'s most famous early melodies.'
        },
        {
            id: 'gq6',
            text: 'What is a "Musical Loop" in game audio?',
            options: [
                { id: 'gq6a1', text: 'A mistake in the recording' },
                { id: 'gq6a2', text: 'A section of music designed to repeat seamlessly for as long as needed' },
                { id: 'gq6a3', text: 'A type of fast rhythm' },
                { id: 'gq6a4', text: 'The end of the game' },
            ],
            correctAnswerId: 'gq6a2',
            explanation: 'Loops are essential for background music in areas where the player might stay for an uncertain amount of time.'
        },
        {
            id: 'gq7',
            text: 'Why is "Symmetry" important in early game melodies (like Mario)?',
            options: [
                { id: 'gq7a1', text: 'To make them hard to remember' },
                { id: 'gq7a2', text: 'To make them "catchy" and memorable despite the simple sound quality' },
                { id: 'gq7a3', text: 'Because computers can only play symmetrical notes' },
                { id: 'gq7a4', text: 'It isn\'t important' },
            ],
            correctAnswerId: 'gq7a2',
            explanation: 'Strong, symmetrical patterns help early chiptunes stay in the player\'s head.'
        },
        {
            id: 'gq8',
            text: 'Which instrument family is often used in RPGs (like Persona or Final Fantasy) to show modern urban life?',
            options: [
                { id: 'gq8a1', text: 'Electric Bass and Synthesizers' },
                { id: 'gq8a2', text: 'Lute and Harpsichord' },
                { id: 'gq8a3', text: 'Church Organ' },
                { id: 'gq8a4', text: 'Bagpipes' },
            ],
            correctAnswerId: 'gq8a1',
            explanation: 'Modern settings often blend Jazz, Rock, and Electronic elements.'
        },
        {
            id: 'gq9',
            text: 'What happens to the music in "Super Mario" when the timer is low?',
            options: [
                { id: 'gq9a1', text: 'It gets slower' },
                { id: 'gq9a2', text: 'It speeds up (Tempo increase)' },
                { id: 'gq9a3', text: 'It stops' },
                { id: 'gq9a4', text: 'It changes key to minor' },
            ],
            correctAnswerId: 'gq9a2',
            explanation: 'Increasing the tempo is a simple but effective way to create player panic and urgency.'
        },
        {
            id: 'gq10',
            text: 'What is "Diegetic Sound" in a game context?',
            options: [
                { id: 'gq10a1', text: 'The HUD menu sounds' },
                { id: 'gq10a2', text: 'Sounds that exist within the game world (e.g., footsteps, a nearby radio)' },
                { id: 'gq10a3', text: 'The main orchestral theme' },
                { id: 'gq10a4', text: 'The voice of the narrator' },
            ],
            correctAnswerId: 'gq10a2',
            explanation: 'If a character in the game can hear it, it is diegetic.'
        },
        {
            id: 'gq11',
            text: 'Mick Gordon\'s score for "DOOM" uses which technique to create "aggression"?',
            options: [
                { id: 'gq11a1', text: 'Soft solo flute' },
                { id: 'gq11a2', text: 'Heavy Distortion and Industrial sound design' },
                { id: 'gq11a3', text: 'A cappella choir' },
                { id: 'gq11a4', text: 'Harpsichord' },
            ],
            correctAnswerId: 'gq11a2',
            explanation: 'Extreme distortion and bass-heavy synthesis match the high-speed combat.'
        },
        {
            id: 'gq12',
            text: 'What is a "Stinger"?',
            options: [
                { id: 'gq12a1', text: 'A long 5-minute song' },
                { id: 'gq12a2', text: 'A very short musical cue triggered by a specific event (e.g., picking up an item)' },
                { id: 'gq12a3', text: 'A type of boss enemy' },
                { id: 'gq12a4', text: 'A broken sound effect' },
            ],
            correctAnswerId: 'gq12a2',
            explanation: 'Stingers provide instant feedback to the player (e.g., "Level Up!" or "Item Found!").'
        },
        {
            id: 'gq13',
            text: 'How does Austin Wintory\'s "Journey" score use its theme?',
            options: [
                { id: 'gq13a1', text: 'It stays exactly the same' },
                { id: 'gq13a2', text: 'The theme evolves from a simple solo cello to a full orchestra as the journey progresses' },
                { id: 'gq13a3', text: 'There is no theme' },
                { id: 'gq13a4', text: 'It uses only pop songs' },
            ],
            correctAnswerId: 'gq13a2',
            explanation: 'This "thematic transformation" mirrors the player\'s growth and the scale of the world.'
        },
        {
            id: 'gq14',
            text: 'What does "Linear Music" mean compared to Adaptive Music?',
            options: [
                { id: 'gq14a1', text: 'Music that you can\'t hear' },
                { id: 'gq14a2', text: 'Music that plays from start to finish without changing based on the player' },
                { id: 'gq14a3', text: 'Music with only one instrument' },
                { id: 'gq14a4', text: 'Music played on a straight line' },
            ],
            correctAnswerId: 'gq14a2',
            explanation: 'Pre-rendered cutscenes usually use linear music, as the timing is fixed.'
        },
        {
            id: 'gq15',
            text: 'In horror games, "Silence" is often used to:',
            options: [
                { id: 'gq15a1', text: 'Save money' },
                { id: 'gq15a2', text: 'Heighten the player\'s senses and create extreme tension' },
                { id: 'gq15a3', text: 'Show that the game is over' },
                { id: 'gq15a4', text: 'Represent a friendly area' },
            ],
            correctAnswerId: 'gq15a2',
            explanation: 'Silence makes every tiny footstep or creak feel threatening.'
        },
        {
            id: 'gq16',
            text: 'What is "Atonality" in a villain theme?',
            options: [
                { id: 'gq16a1', text: 'A very catchy jingle' },
                { id: 'gq16a2', text: 'Music that lacks a clear home key or "tonic," feeling unstable and creepy' },
                { id: 'gq16a3', text: 'Music with only two notes' },
                { id: 'gq16a4', text: 'A happy song' },
            ],
            correctAnswerId: 'gq16a2',
            explanation: 'Atonality is perfect for representing madness or alien threats.'
        },
        {
            id: 'gq17',
            text: 'Which instrument family often provides the "foundation" for epic fantasy boss music?',
            options: [
                { id: 'gq17a1', text: 'Solo Piccolo' },
                { id: 'gq17a2', text: 'Low Brass and Large Percussion (Timpani/Taiko)' },
                { id: 'gq17a3', text: 'Ukulele' },
                { id: 'gq17a4', text: 'Recorder' },
            ],
            correctAnswerId: 'gq17a2',
            explanation: 'Low brass and thunderous percussion create a sense of scale and power.'
        },
        {
            id: 'gq18',
            text: 'What is "Vertical Layering" in a stealth game?',
            options: [
                { id: 'gq18a1', text: 'Fading in a "tension" layer (like a rapid heart-beat pulse) as you get closer to enemies' },
                { id: 'gq18a2', text: 'Playing the music from the floor up' },
                { id: 'gq18a3', text: 'Deleting the game' },
                { id: 'gq18a4', text: 'A type of dance' },
            ],
            correctAnswerId: 'gq18a1',
            explanation: 'This dynamic shift warns the player of danger without stopping the primary music.'
        },
        {
            id: 'gq19',
            text: 'Which composer is known for the epic "Halo" choir themes?',
            options: [
                { id: 'gq19a1', text: 'Marty O\'Donnell' },
                { id: 'gq19a2', text: 'John Williams' },
                { id: 'gq19a3', text: 'Elvis' },
                { id: 'gq19a4', text: 'Hans Zimmer' },
            ],
            correctAnswerId: 'gq19a1',
            explanation: 'O\'Donnell used Gregorian-style chanting to give the game a sense of "ancient mystery."'
        },
        {
            id: 'gq20',
            text: 'If you hear a fast, syncopated ostinato in a racing game, it is meant to:',
            options: [
                { id: 'gq20a1', text: 'Make you feel relaxed' },
                { id: 'gq20a2', text: 'Create a sense of high speed and forward momentum' },
                { id: 'gq20a3', text: 'Tell a sad story' },
                { id: 'gq20a4', text: 'Remind you of grandma' },
            ],
            correctAnswerId: 'gq20a2',
            explanation: 'High tempo and repetition drive the player\'s focus and energy.'
        }
    ]
};

const StageScreen0310GameMusicPage: React.FC = () => {
    return (
        <article className="max-w-4xl mx-auto px-4 py-8">
            {/* Breadcrumb Navigation */}
            <nav className="mb-6 text-sm text-gray-500 dark:text-gray-400">
                <Link to="/" className="hover:text-emerald-600 dark:hover:text-emerald-400">Home</Link>
                <span className="mx-2">›</span>
                <Link to="/aos/stage-screen" className="hover:text-emerald-600 dark:hover:text-emerald-400">Music for Stage and Screen</Link>
                <span className="mx-2">›</span>
                <span className="text-gray-700 dark:text-gray-300">Video Game Music</span>
            </nav>

            {/* Page Header */}
            <header className="mb-10 text-center">
                <div className="inline-block px-4 py-1.5 mb-4 rounded-full bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-300 text-sm font-bold tracking-widest uppercase">
                    Focus Area
                </div>
                <h1 className="text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-emerald-600 to-teal-600 mb-4">
                    Video Game Music
                </h1>
                <p className="text-xl text-gray-600 dark:text-gray-400 font-medium">
                    The Frontier of Interactive Audio
                </p>
            </header>

            {/* Main Content */}
            <div className="prose prose-slate dark:prose-invert max-w-none space-y-12">
                <section className="bg-white dark:bg-slate-800 rounded-3xl p-8 shadow-xl border border-emerald-100 dark:border-emerald-900/40">
                    <h2 className="text-3xl font-bold mb-6 text-emerald-700 dark:text-emerald-400">Reactive Worlds</h2>
                    <p className="text-lg leading-relaxed">
                        Video Game music is fundamentally different from film or ballet because it is
                        <strong>interactive</strong>. The music doesn't know how long a fight will last
                        or which way a player will turn, so it must be built to <strong>react in real-time</strong>.
                    </p>
                </section>

                <section>
                    <h2 className="text-3xl font-bold mb-6">1. Adaptive Music Systems</h2>
                    <div className="grid md:grid-cols-2 gap-8">
                        <div className="bg-slate-50 dark:bg-slate-900/50 p-6 rounded-2xl border-b-4 border-emerald-600">
                            <h3 className="font-bold text-xl mb-2">Vertical Layering</h3>
                            <p className="text-sm">
                                Individual tracks (drums, bass, melodies) are faded in or out depending on the
                                intensity of the gameplay.
                            </p>
                        </div>
                        <div className="bg-slate-50 dark:bg-slate-900/50 p-6 rounded-2xl border-b-4 border-teal-600">
                            <h3 className="font-bold text-xl mb-2">Horizontal Re-sequencing</h3>
                            <p className="text-sm">
                                The game engine's jumping between different musical "loops" at the end of a bar to
                                change the location or situation seamlessly.
                            </p>
                        </div>
                    </div>
                </section>

                <section>
                    <h2 className="text-3xl font-bold mb-6">2. From Beeps to Orchestras</h2>
                    <p className="mb-6">
                        Early games used <strong>Chiptune</strong> synthesis (8-bit), which relied on
                        unforgettable, symmetrical melodies to overcome the technical limits.
                    </p>

                    <AbcDisplayComponent
                        id="retro-theme"
                        title="Symmetrical 8-Bit Style Melody"
                        abcNotation={`X:1\nM:4/4\nL:1/8\nK:C\nQ:" Retro Pulse"\nG E C D | E G C2 | G E C D | E D C2 |`}
                    />

                    <div className="mt-8 bg-emerald-50 dark:bg-emerald-900/20 p-6 rounded-2xl border border-emerald-100 dark:border-emerald-800">
                        <h4 className="font-bold mb-2">Modern Hybrid Scores</h4>
                        <p className="text-sm">
                            Today, games use <strong>Full Orchestral</strong> scores recorded in the same studios
                            as Hollywood movies, often blended with complex electronic sound design.
                        </p>
                    </div>
                </section>

                <section className="bg-emerald-900 text-white p-8 rounded-3xl shadow-2xl">
                    <h2 className="text-3xl font-bold mb-6 text-emerald-200">The Power of the "Stinger"</h2>
                    <p className="mb-4 leading-relaxed">
                        A <strong>Stinger</strong> is a short burst of music (2-5 seconds) that gives the player
                        instant feedback.
                    </p>
                    <ul className="list-disc pl-6 space-y-2 opacity-90">
                        <li><strong>Level Up:</strong> A bright, rising fanfare.</li>
                        <li><strong>Death:</strong> A low, dark, dissonant chord.</li>
                        <li><strong>Item Found:</strong> A shimmering, high-pitched chime.</li>
                    </ul>
                </section>

                <section className="py-12">
                    <h2 className="text-4xl font-black text-center mb-12 uppercase tracking-tighter text-emerald-800 dark:text-emerald-200">Video Game Quiz</h2>
                    <p className="text-center text-gray-500 mb-8 font-medium italic text-lg">20 Questions to Level Up your knowledge</p>
                    <QuizComponent quizData={gameQuiz} />
                </section>
            </div>

            <footer className="mt-16 pt-8 border-t border-gray-200 dark:border-slate-800 text-center">
                <Link to="/aos/stage-screen/core-musical-elements/melody" className="inline-flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white font-bold py-3 px-8 rounded-full transition-all hover:scale-105">
                    Back to Core Musical Elements
                    <span>→</span>
                </Link>
            </footer>
        </article>
    );
};

export default StageScreen0310GameMusicPage;
