
import { SyllabusItem } from '../../types';

export const examPractice: SyllabusItem = {
    id: 'exam-practice',
    title: 'Exam Practice',
    title_zh: '考试练习',
    path: '/exam-practice',
    content: 'Practice exams for 1st and 2nd year students.',
    content_zh: '一年级和二年级学生的模拟考试。',
    longDescription: 'Comprehensive exam practice resources organized by year group.',
    longDescription_zh: '按年级组织的综合考试练习资源。',
    children: [
        {
            id: '1st-year',
            title: '1st Year',
            title_zh: '一年级',
            path: '/exam-practice/1st-year',
            content: 'Mock exams for 1st Year.',
            content_zh: '一年级模拟考试。',
            longDescription: 'Practice materials for 1st year students.',
            longDescription_zh: '一年级学生的练习材料。',
            children: [
                {
                    id: '1st-year-mock-1',
                    title: 'Mock 1',
                    title_zh: '模拟一',
                    path: '/exam-practice/1st-year/mock-1',
                    content: 'First mock exam for 1st Year.',
                    content_zh: '一年级第一次模拟考试。',
                    longDescription: 'Full mock exam paper 1.',
                    longDescription_zh: '第一份完整模拟试卷。',
                },
                {
                    id: '1st-year-mock-2',
                    title: 'Mock 2',
                    title_zh: '模拟二',
                    path: '/exam-practice/1st-year/mock-2',
                    content: 'Second mock exam for 1st Year.',
                    content_zh: '一年级第二次模拟考试。',
                    longDescription: 'Full mock exam paper 2.',
                    longDescription_zh: '第二份完整模拟试卷。',
                },
            ],
        },
        {
            id: '2nd-year',
            title: '2nd Year',
            title_zh: '二年级',
            path: '/exam-practice/2nd-year',
            content: 'Mock exams for 2nd Year.',
            content_zh: '二年级模拟考试。',
            longDescription: 'Practice materials for 2nd year students.',
            longDescription_zh: '二年级学生的练习材料。',
            children: [
                {
                    id: '2nd-year-mock-1',
                    title: 'Mock 1',
                    title_zh: '模拟一',
                    path: '/exam-practice/2nd-year/mock-1',
                    content: 'First mock exam for 2nd Year.',
                    content_zh: '二年级第一次模拟考试。',
                    longDescription: 'Full mock exam paper 1.',
                    longDescription_zh: '第一份完整模拟试卷。',
                },
                {
                    id: '2nd-year-mock-2',
                    title: 'Mock 2',
                    title_zh: '模拟二',
                    path: '/exam-practice/2nd-year/mock-2',
                    content: 'Second mock exam for 2nd Year.',
                    content_zh: '二年级第二次模拟考试。',
                    longDescription: 'Full mock exam paper 2.',
                    longDescription_zh: '第二份完整模拟试卷。',
                },
            ],
        },
    ],
};
