import { SyllabusItem } from '../../types';

export const examPractice: SyllabusItem = {
    id: 'exam-practice',
    title: 'Exam Practice',
    title_zh: '考试练习',
    path: '/exam-practice',
    content: 'Practice exams for 1st and 2nd year students.',
    content_zh: '一年级和二年级学生的模拟考试。',
    longDescription: 'Comprehensive exam practice resources organized by year group.',
    longDescription_zh: '按年级组织的综合考试练习资源。',
    children: [
        {
            id: '1st-year',
            title: '1st Year',
            title_zh: '一年级',
            path: '/exam-practice/1st-year',
            content: 'Mock exams for 1st Year.',
            content_zh: '一年级模拟考试。',
            longDescription: 'Practice materials for 1st year students.',
            longDescription_zh: '一年级学生的练习材料。',
            children: [
                {
                    id: '1st-year-mock-1',
                    title: 'Mock 1',
                    title_zh: '模拟一',
                    path: '/exam-practice/1st-year/mock-1',
                    content: 'First mock exam for 1st Year.',
                    content_zh: '一年级第一次模拟考试。',
                    longDescription: 'Full mock exam paper 1.',
                    longDescription_zh: '第一份完整模拟试卷。',
                },
                {
                    id: '1st-year-mock-2',
                    title: 'Mock 2',
                    title_zh: '模拟二',
                    path: '/exam-practice/1st-year/mock-2',
                    content: 'Second mock exam for 1st Year.',
                    content_zh: '一年级第二次模拟考试。',
                    longDescription: 'Full mock exam paper 2.',
                    longDescription_zh: '第二份完整模拟试卷。',
                },
            ],
        },
        {
            id: '2nd-year',
            title: '2nd Year (G10)',
            title_zh: '二年级 (G10)',
            path: '/exam-practice/2nd-year',
            content: 'Mock exams for 2nd Year (G10).',
            content_zh: '二年级 (G10) 模拟考试。',
            longDescription: 'Practice materials for 2nd year (G10) students.',
            longDescription_zh: '二年级 (G10) 学生的练习材料。',
            children: [
                {
                    id: '2nd-year-mock-1',
                    title: 'Mock 1 - Revision Quizzes',
                    title_zh: '模拟一 - 复习测验',
                    path: '/exam-practice/2nd-year/mock-1',
                    content: 'Revision practice quizzes for 2nd Year.',
                    content_zh: '二年级复习练习测验。',
                    longDescription: 'Topic-based revision quizzes with ABC notation audio.',
                    longDescription_zh: '基于主题的复习测验，包含ABC乐谱音频。',
                    children: [
                        {
                            id: 'quiz-tonality',
                            title: 'Architecture of Tonality',
                            title_zh: '调性结构',
                            path: '/exam-practice/2nd-year/mock-1/tonality',
                            content: 'Quiz on tonality, clefs, accidentals, and scale degrees.',
                            content_zh: '关于调性、谱号、临时记号和音阶级数的测验。',
                            longDescription: '20 MCQ questions testing knowledge of tonality concepts.',
                            longDescription_zh: '20道选择题，测试调性概念知识。',
                        },
                        {
                            id: 'quiz-texture-basics',
                            title: 'Types of Musical Texture',
                            title_zh: '音乐织体类型',
                            path: '/exam-practice/2nd-year/mock-1/texture-basics',
                            content: 'Quiz on monophony, homophony, polyphony, and heterophony.',
                            content_zh: '关于单声部、主调、复调和异声的测验。',
                            longDescription: '20 MCQ questions on the four main texture types.',
                            longDescription_zh: '20道选择题，测试四种主要织体类型。',
                        },
                        {
                            id: 'quiz-texture-detailed',
                            title: 'Musical Texture (Detailed)',
                            title_zh: '音乐织体（详细）',
                            path: '/exam-practice/2nd-year/mock-1/texture-detailed',
                            content: 'Advanced quiz on texture with score analysis.',
                            content_zh: '关于织体的高级测验，包含乐谱分析。',
                            longDescription: '20 MCQ questions with deeper analysis of texture.',
                            longDescription_zh: '20道选择题，深入分析织体。',
                        },
                        {
                            id: 'quiz-texture-strategies',
                            title: 'Identifying Texture Strategies',
                            title_zh: '识别织体策略',
                            path: '/exam-practice/2nd-year/mock-1/texture-strategies',
                            content: 'Quiz on strategies for identifying texture in exams.',
                            content_zh: '关于考试中识别织体策略的测验。',
                            longDescription: '20 MCQ questions on texture identification techniques.',
                            longDescription_zh: '20道选择题，测试织体识别技巧。',
                        },
                    ],
                },
                {
                    id: '2nd-year-mock-2',
                    title: 'Mock 2',
                    title_zh: '模拟二',
                    path: '/exam-practice/2nd-year/mock-2',
                    content: 'Second mock exam for 2nd Year.',
                    content_zh: '二年级第二次模拟考试。',
                    longDescription: 'Full mock exam paper 2.',
                    longDescription_zh: '第二份完整模拟试卷。',
                },
            ],
        },
    ],
};
