import React from 'react';
import { Link } from 'react-router-dom';

const Ch24BinaryandternarypracticeexercisesPage: React.FC = () => {
  return (
    <article className="max-w-4xl mx-auto px-4 py-8">
      {/* Breadcrumb Navigation */}
      <nav className="mb-6 text-sm text-gray-500 dark:text-gray-400">
        <Link to="/" className="hover:text-sky-600 dark:hover:text-sky-400">Home</Link>
        <span className="mx-2">›</span>
        <Link to="/theory" className="hover:text-sky-600 dark:hover:text-sky-400">Theory</Link>
        <span className="mx-2">›</span>
        <span className="text-gray-600 dark:text-gray-300">Ch. 24</span>
        <span className="mx-2">›</span>
        <span className="text-gray-700 dark:text-gray-300">Practice Exercises</span>
      </nav>

      {/* Page Header */}
      <header className="mb-10">
        <div className="flex items-center gap-3 mb-2">
          <span className="px-3 py-1 bg-sky-100 dark:bg-sky-900 text-sky-700 dark:text-sky-300 rounded-full text-sm font-medium">
            Chapter 24
          </span>
          <span className="text-gray-500 dark:text-gray-400 text-sm">
            Binary & Ternary Form
          </span>
        </div>
        <h1 className="text-3xl md:text-4xl font-bold text-slate-800 dark:text-slate-100">
          Practice Exercises
        </h1>
      </header>

      {/* Main Content */}
      <div className="prose prose-slate dark:prose-invert max-w-none
        prose-headings:text-slate-800 dark:prose-headings:text-slate-100
        prose-h2:text-2xl prose-h2:font-bold prose-h2:border-b prose-h2:border-slate-200 dark:prose-h2:border-slate-700 prose-h2:pb-2 prose-h2:mb-4
        prose-h3:text-xl prose-h3:font-semibold
        prose-h4:text-lg prose-h4:font-medium
        prose-p:text-gray-700 dark:prose-p:text-gray-300 prose-p:leading-relaxed
        prose-li:text-gray-700 dark:prose-li:text-gray-300
        prose-strong:text-slate-800 dark:prose-strong:text-slate-200
        prose-a:text-sky-600 dark:prose-a:text-sky-400 prose-a:hover:underline
        prose-img:rounded-lg prose-img:shadow-md prose-img:mx-auto
        prose-figure:my-6
        prose-figcaption:text-center prose-figcaption:text-sm prose-figcaption:text-gray-500 dark:prose-figcaption:text-gray-400
        [&_section]:mb-8 [&_section]:bg-slate-50 dark:[&_section]:bg-slate-800/50 [&_section]:rounded-lg [&_section]:p-6
        [&_table]:w-full [&_th]:bg-slate-100 dark:[&_th]:bg-slate-700 [&_th]:p-2 [&_td]:p-2 [&_td]:border [&_td]:border-slate-200 dark:[&_td]:border-slate-600
      ">
        <div dangerouslySetInnerHTML={{ __html: `<div id="ptx-content" className="ptx-content"><section className="exercises" id="BinaryAndTernaryPracticeExercises"><h2 className="heading hide-type">
<span className="type">Exercises</span><span className="space heading-divison-mark heading-divison-mark__space"> </span><span className="codenumber">24.9</span><span className="space heading-divison-mark heading-divison-mark__space"> </span><span className="title">Practice Exercises</span>
</h2>
<div className="exercisegroup" id="BinaryAndTernaryPracticeExercises-2">
<h3 className="heading"><span className="title">Exercise Group.</span></h3>
<div className="introduction" id="BinaryAndTernaryPracticeExercises-2-1"><div className="para" id="BinaryAndTernaryPracticeExercises-2-1-1">Day One<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-2-1-1" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div></div>
<div className="exercisegroup-exercises">
<article className="exercise exercise-like" id="BinaryAndTernaryPracticeExercises-2-2"><h4 className="heading"><span className="codenumber">1<span className="period heading-divison-mark heading-divison-mark__period">.</span></span></h4>
<div className="para" id="BinaryAndTernaryPracticeExercises-2-2-1-1">For Handel’s Gavotte, HWV 491, please fill in the blanks below the staves and diagram the form. Also, name the form. You will need to determine which notes are non-chord tones in order to determine Roman numerals.<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-2-2-1-1" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div>  <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Handel-gavotte-A.svg" role="img" className="contained" alt="" /></div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Handel-gavotte-B.svg" role="img" className="contained" alt="" /></div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Handel-gavotte-C.svg" role="img" className="contained" alt="" /></div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Handel-gavotte-D.svg" role="img" className="contained" alt="" /></div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Handel-gavotte-E.svg" role="img" className="contained" alt="" /></div> <div className="video-box">
<div onclick="this.nextElementSibling.style.display='block'; this.style.display='none'"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 14 96 68" preserveAspectRatio="none"><path fill="#e62117" d="M94.98,28.84c0,0-0.94-6.6-3.81-9.5c-3.64-3.81-7.72-3.83-9.59-4.05c-13.4-0.97-33.52-0.85-33.52-0.85s-20.12-0.12-33.52,0.85c-1.87,0.22-5.95,0.24-9.59,4.05c-2.87,2.9-3.81,9.5-3.81,9.5S0.18,36.58,0,44.33v7.26c0.18,7.75,1.14,15.49,1.14,15.49s0.93,6.6,3.81,9.5c3.64,3.81,8.43,3.69,10.56,4.09c7.53,0.72,31.7,0.89,32.54,0.9c0.01,0,20.14,0.03,33.54-0.94c1.87-0.22,5.95-0.24,9.59-4.05c2.87-2.9,3.81-9.5,3.81-9.5s0.96-7.75,1.02-15.49v-7.26C95.94,36.58,94.98,28.84,94.98,28.84z M38.28,61.41v-27l25.74,13.5L38.28,61.41z"></path></svg></div>
<div className="hidden-content"><iframe className="video" allowfullscreen="" src="https://www.youtube-nocookie.com/embed/vCwTTyz35lw?&amp;modestbranding=1&amp;rel=0&amp;start=0&amp;end=56" id="BinaryAndTernaryPracticeExercises-2-2-1-8"></iframe></div>
</div> <figure className="figure figure-like" id="BinaryAndTernaryPracticeExercises-2-2-1-9"><figcaption><span className="type">Figure</span><span className="space heading-divison-mark heading-divison-mark__space"> </span><span className="codenumber">24.9.1<span className="period heading-divison-mark heading-divison-mark__period">.</span></span><span className="space heading-divison-mark heading-divison-mark__space"> </span>George Frideric Handel, Gavotte, HWV 491<div className="autopermalink" data-description="Figure 24.9.1"><a href="#BinaryAndTernaryPracticeExercises-2-2-1-9" title="Copy heading and permalink for Figure 24.9.1" aria-label="Copy heading and permalink for Figure 24.9.1">🔗</a></div></figcaption></figure> <div className="para" id="BinaryAndTernaryPracticeExercises-2-2-1-10">For the piece above, complete the following diagram based on your analysis. Include section labels using uppercase letters, phrase labels using lowercase letters, and cadences using the abbreviations PAC, IAC, HC, DC, PC.<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-2-2-1-10" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div> <div className="image-box"><img src="/theory/external/images/unit7/PRAC-EXER-handel-gavotte-DIAGRAM.svg" role="img" className="contained" /></div> <div className="para" id="BinaryAndTernaryPracticeExercises-2-2-1-12">Circle all of the terms that apply to the name of the form:<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-2-2-1-12" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div> <div className="image-box"><img src="/theory/external/images/unit7/PRAC-EXER-bin-tern-terms-to-circle.svg" role="img" className="contained" /></div>
<div className="solutions"><details id="BinaryAndTernaryPracticeExercises-2-2-2" className="answer solution-like born-hidden-knowl"><summary className="knowl__link"><span className="type">Answer</span><span className="period heading-divison-mark heading-divison-mark__period">.</span></summary><div className="answer solution-like knowl__content">
<div className="image-box"><img src="/theory/external/images/unit7/PRAC-EXER-handel-gavotte-DIAGRAM-KEY.svg" role="img" className="contained" /></div>
<div className="image-box"><img src="/theory/external/images/unit7/PRAC-EXER-bin-tern-Handel-terms-to-circle-KEY.svg" role="img" className="contained" /></div>
<div className="autopermalink" data-description="Answer 24.9.1.1"><a href="#BinaryAndTernaryPracticeExercises-2-2-2" title="Copy heading and permalink for Answer 24.9.1.1" aria-label="Copy heading and permalink for Answer 24.9.1.1">🔗</a></div>
</div></details></div>
<div className="autopermalink" data-description="Exercise 24.9.1"><a href="#BinaryAndTernaryPracticeExercises-2-2" title="Copy heading and permalink for Exercise 24.9.1" aria-label="Copy heading and permalink for Exercise 24.9.1">🔗</a></div></article><article className="exercise exercise-like" id="BinaryAndTernaryPracticeExercises-2-3"><h4 className="heading"><span className="codenumber">2<span className="period heading-divison-mark heading-divison-mark__period">.</span></span></h4>
<div className="para" id="BinaryAndTernaryPracticeExercises-2-3-1-1">For the theme from first movement of Mozart’s Piano Sonata in A major, K. 331, please fill in the blanks below the staves and diagram the form. Also, name the form.<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-2-3-1-1" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div>  <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Mozart-K331-A.svg" role="img" className="contained" alt="" /></div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Mozart-K331-B.svg" role="img" className="contained" alt="" /></div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Mozart-K331-C.svg" role="img" className="contained" alt="" /></div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Mozart-K331-D.svg" role="img" className="contained" alt="" /></div> <div className="video-box">
<div onclick="this.nextElementSibling.style.display='block'; this.style.display='none'"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 14 96 68" preserveAspectRatio="none"><path fill="#e62117" d="M94.98,28.84c0,0-0.94-6.6-3.81-9.5c-3.64-3.81-7.72-3.83-9.59-4.05c-13.4-0.97-33.52-0.85-33.52-0.85s-20.12-0.12-33.52,0.85c-1.87,0.22-5.95,0.24-9.59,4.05c-2.87,2.9-3.81,9.5-3.81,9.5S0.18,36.58,0,44.33v7.26c0.18,7.75,1.14,15.49,1.14,15.49s0.93,6.6,3.81,9.5c3.64,3.81,8.43,3.69,10.56,4.09c7.53,0.72,31.7,0.89,32.54,0.9c0.01,0,20.14,0.03,33.54-0.94c1.87-0.22,5.95-0.24,9.59-4.05c2.87-2.9,3.81-9.5,3.81-9.5s0.96-7.75,1.02-15.49v-7.26C95.94,36.58,94.98,28.84,94.98,28.84z M38.28,61.41v-27l25.74,13.5L38.28,61.41z"></path></svg></div>
<div className="hidden-content"><iframe className="video" allowfullscreen="" src="https://www.youtube-nocookie.com/embed/vp_h649sZ9A?&amp;modestbranding=1&amp;rel=0&amp;start=3&amp;end=51" id="BinaryAndTernaryPracticeExercises-2-3-1-7"></iframe></div>
</div> <figure className="figure figure-like" id="BinaryAndTernaryPracticeExercises-2-3-1-8"><figcaption><span className="type">Figure</span><span className="space heading-divison-mark heading-divison-mark__space"> </span><span className="codenumber">24.9.2<span className="period heading-divison-mark heading-divison-mark__period">.</span></span><span className="space heading-divison-mark heading-divison-mark__space"> </span>Mozart, Piano Sonata K. 331, I<div className="autopermalink" data-description="Figure 24.9.2"><a href="#BinaryAndTernaryPracticeExercises-2-3-1-8" title="Copy heading and permalink for Figure 24.9.2" aria-label="Copy heading and permalink for Figure 24.9.2">🔗</a></div></figcaption></figure> <div className="para" id="BinaryAndTernaryPracticeExercises-2-3-1-9">For the piece above, complete the following diagram based on your analysis. Include section labels using uppercase letters, phrase labels using lowercase letters, and cadences using the abbreviations PAC, IAC, HC, DC, PC.<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-2-3-1-9" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div> <div className="image-box"><img src="/theory/external/images/unit7/PRAC-EXER-mozart-331-DIAGRAM.svg" role="img" className="contained" /></div> <div className="para" id="BinaryAndTernaryPracticeExercises-2-3-1-11">Circle all of the terms that apply to the name of the form:<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-2-3-1-11" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div> <div className="image-box"><img src="/theory/external/images/unit7/PRAC-EXER-bin-tern-terms-to-circle.svg" role="img" className="contained" /></div>
<div className="solutions"><details id="BinaryAndTernaryPracticeExercises-2-3-2" className="answer solution-like born-hidden-knowl"><summary className="knowl__link"><span className="type">Answer</span><span className="period heading-divison-mark heading-divison-mark__period">.</span></summary><div className="answer solution-like knowl__content">
<div className="image-box"><img src="/theory/external/images/unit7/PRAC-EXER-mozart-331-DIAGRAM-KEY.svg" role="img" className="contained" /></div>
<div className="image-box"><img src="/theory/external/images/unit7/PRAC-EXER-bin-tern-Mozart331-terms-to-circle-KEY.svg" role="img" className="contained" /></div>
<div className="autopermalink" data-description="Answer 24.9.2.1"><a href="#BinaryAndTernaryPracticeExercises-2-3-2" title="Copy heading and permalink for Answer 24.9.2.1" aria-label="Copy heading and permalink for Answer 24.9.2.1">🔗</a></div>
</div></details></div>
<div className="autopermalink" data-description="Exercise 24.9.2"><a href="#BinaryAndTernaryPracticeExercises-2-3" title="Copy heading and permalink for Exercise 24.9.2" aria-label="Copy heading and permalink for Exercise 24.9.2">🔗</a></div></article>
</div>
<div className="autopermalink" data-description="Exercise Group 24.9.1–2"><a href="#BinaryAndTernaryPracticeExercises-2" title="Copy heading and permalink for Exercise Group 24.9.1–2" aria-label="Copy heading and permalink for Exercise Group 24.9.1–2">🔗</a></div>
</div>
<div className="exercisegroup" id="BinaryAndTernaryPracticeExercises-3">
<h3 className="heading"><span className="title">Exercise Group.</span></h3>
<div className="introduction" id="BinaryAndTernaryPracticeExercises-3-1"><div className="para" id="BinaryAndTernaryPracticeExercises-3-1-1">Day Two<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-3-1-1" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div></div>
<div className="exercisegroup-exercises">
<article className="exercise exercise-like" id="BinaryAndTernaryPracticeExercises-3-2"><h4 className="heading"><span className="codenumber">3<span className="period heading-divison-mark heading-divison-mark__period">.</span></span></h4>
<div className="para" id="BinaryAndTernaryPracticeExercises-3-2-1-1">For this Polonaise in F major by Mozart, please fill in the blanks below the staves and diagram the form. Also, name the form.<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-3-2-1-1" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Mozart-Polonaise-A.svg" role="img" className="contained" alt="" /></div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Mozart-Polonaise-B.svg" role="img" className="contained" alt="" /></div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Mozart-Polonaise-C.svg" role="img" className="contained" alt="" /></div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Mozart-Polonaise-D.svg" role="img" className="contained" alt="" /></div> <div className="video-box">
<div onclick="this.nextElementSibling.style.display='block'; this.style.display='none'"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 14 96 68" preserveAspectRatio="none"><path fill="#e62117" d="M94.98,28.84c0,0-0.94-6.6-3.81-9.5c-3.64-3.81-7.72-3.83-9.59-4.05c-13.4-0.97-33.52-0.85-33.52-0.85s-20.12-0.12-33.52,0.85c-1.87,0.22-5.95,0.24-9.59,4.05c-2.87,2.9-3.81,9.5-3.81,9.5S0.18,36.58,0,44.33v7.26c0.18,7.75,1.14,15.49,1.14,15.49s0.93,6.6,3.81,9.5c3.64,3.81,8.43,3.69,10.56,4.09c7.53,0.72,31.7,0.89,32.54,0.9c0.01,0,20.14,0.03,33.54-0.94c1.87-0.22,5.95-0.24,9.59-4.05c2.87-2.9,3.81-9.5,3.81-9.5s0.96-7.75,1.02-15.49v-7.26C95.94,36.58,94.98,28.84,94.98,28.84z M38.28,61.41v-27l25.74,13.5L38.28,61.41z"></path></svg></div>
<div className="hidden-content"><iframe className="video" allowfullscreen="" src="https://www.youtube-nocookie.com/embed/6J2OpIjODTU?&amp;modestbranding=1&amp;rel=0&amp;start=0&amp;end=42" id="BinaryAndTernaryPracticeExercises-3-2-1-6"></iframe></div>
</div> <figure className="figure figure-like" id="BinaryAndTernaryPracticeExercises-3-2-1-7"><figcaption><span className="type">Figure</span><span className="space heading-divison-mark heading-divison-mark__space"> </span><span className="codenumber">24.9.3<span className="period heading-divison-mark heading-divison-mark__period">.</span></span><span className="space heading-divison-mark heading-divison-mark__space"> </span>Mozart, Polonaise in F major<div className="autopermalink" data-description="Figure 24.9.3"><a href="#BinaryAndTernaryPracticeExercises-3-2-1-7" title="Copy heading and permalink for Figure 24.9.3" aria-label="Copy heading and permalink for Figure 24.9.3">🔗</a></div></figcaption></figure> <div className="para" id="BinaryAndTernaryPracticeExercises-3-2-1-8">For the piece above, complete the following diagram based on your analysis. Include section labels using uppercase letters, phrase labels using lowercase letters, and cadences using the abbreviations PAC, IAC, HC, DC, PC.<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-3-2-1-8" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div> <div className="image-box"><img src="/theory/external/images/unit7/PRAC-EXER-mozart-331-DIAGRAM.svg" role="img" className="contained" /></div> <div className="para" id="BinaryAndTernaryPracticeExercises-3-2-1-10">Circle all of the terms that apply to the name of the form:<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-3-2-1-10" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div> <div className="image-box"><img src="/theory/external/images/unit7/PRAC-EXER-bin-tern-terms-to-circle.svg" role="img" className="contained" /></div>
<div className="solutions"><details id="BinaryAndTernaryPracticeExercises-3-2-2" className="answer solution-like born-hidden-knowl"><summary className="knowl__link"><span className="type">Answer</span><span className="period heading-divison-mark heading-divison-mark__period">.</span></summary><div className="answer solution-like knowl__content">
<div className="image-box"><img src="/theory/external/images/unit7/PRAC-EXER-mozart-331-DIAGRAM-KEY.svg" role="img" className="contained" /></div>
<div className="image-box"><img src="/theory/external/images/unit7/PRAC-EXER-bin-tern-Mozart331-terms-to-circle-KEY.svg" role="img" className="contained" /></div>
<div className="autopermalink" data-description="Answer 24.9.3.1"><a href="#BinaryAndTernaryPracticeExercises-3-2-2" title="Copy heading and permalink for Answer 24.9.3.1" aria-label="Copy heading and permalink for Answer 24.9.3.1">🔗</a></div>
</div></details></div>
<div className="autopermalink" data-description="Exercise 24.9.3"><a href="#BinaryAndTernaryPracticeExercises-3-2" title="Copy heading and permalink for Exercise 24.9.3" aria-label="Copy heading and permalink for Exercise 24.9.3">🔗</a></div></article><article className="exercise exercise-like" id="BinaryAndTernaryPracticeExercises-3-3"><h4 className="heading"><span className="codenumber">4<span className="period heading-divison-mark heading-divison-mark__period">.</span></span></h4>
<div className="para" id="BinaryAndTernaryPracticeExercises-3-3-1-1">For this Allegro in B-flat major (K. 3) by Mozart, please fill in the blanks below the staves and diagram the form. Also, name the form.<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-3-3-1-1" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Moz-allegro-in-Bflat-A.svg" role="img" className="contained" alt="" /></div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Moz-allegro-in-Bflat-B.svg" role="img" className="contained" alt="" /></div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Moz-allegro-in-Bflat-C.svg" role="img" className="contained" alt="" /></div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Moz-allegro-in-Bflat-D.svg" role="img" className="contained" alt="" /></div> <div className="video-box">
<div onclick="this.nextElementSibling.style.display='block'; this.style.display='none'"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 14 96 68" preserveAspectRatio="none"><path fill="#e62117" d="M94.98,28.84c0,0-0.94-6.6-3.81-9.5c-3.64-3.81-7.72-3.83-9.59-4.05c-13.4-0.97-33.52-0.85-33.52-0.85s-20.12-0.12-33.52,0.85c-1.87,0.22-5.95,0.24-9.59,4.05c-2.87,2.9-3.81,9.5-3.81,9.5S0.18,36.58,0,44.33v7.26c0.18,7.75,1.14,15.49,1.14,15.49s0.93,6.6,3.81,9.5c3.64,3.81,8.43,3.69,10.56,4.09c7.53,0.72,31.7,0.89,32.54,0.9c0.01,0,20.14,0.03,33.54-0.94c1.87-0.22,5.95-0.24,9.59-4.05c2.87-2.9,3.81-9.5,3.81-9.5s0.96-7.75,1.02-15.49v-7.26C95.94,36.58,94.98,28.84,94.98,28.84z M38.28,61.41v-27l25.74,13.5L38.28,61.41z"></path></svg></div>
<div className="hidden-content"><iframe className="video" allowfullscreen="" src="https://www.youtube-nocookie.com/embed/t5R0ORjKloE?&amp;modestbranding=1&amp;rel=0&amp;start=2&amp;end=49" id="BinaryAndTernaryPracticeExercises-3-3-1-6"></iframe></div>
</div> <figure className="figure figure-like" id="BinaryAndTernaryPracticeExercises-3-3-1-7"><figcaption><span className="type">Figure</span><span className="space heading-divison-mark heading-divison-mark__space"> </span><span className="codenumber">24.9.4<span className="period heading-divison-mark heading-divison-mark__period">.</span></span><span className="space heading-divison-mark heading-divison-mark__space"> </span>Mozart, Allegro in B-flat major<div className="autopermalink" data-description="Figure 24.9.4"><a href="#BinaryAndTernaryPracticeExercises-3-3-1-7" title="Copy heading and permalink for Figure 24.9.4" aria-label="Copy heading and permalink for Figure 24.9.4">🔗</a></div></figcaption></figure> <div className="para" id="BinaryAndTernaryPracticeExercises-3-3-1-8">On scratch paper, create a diagram of the form. Include section labels using uppercase letters, phrase labels using lowercase letters, and cadences using the abbreviations PAC, IAC, HC, DC, PC.<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-3-3-1-8" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div> <div className="para" id="BinaryAndTernaryPracticeExercises-3-3-1-9">Circle all of the terms that apply to the name of the form:<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-3-3-1-9" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div> <div className="image-box"><img src="/theory/external/images/unit7/PRAC-EXER-bin-tern-terms-to-circle.svg" role="img" className="contained" /></div>
<div className="solutions"><details id="BinaryAndTernaryPracticeExercises-3-3-2" className="answer solution-like born-hidden-knowl"><summary className="knowl__link"><span className="type">Answer</span><span className="period heading-divison-mark heading-divison-mark__period">.</span></summary><div className="answer solution-like knowl__content">
<div className="image-box"><img src="/theory/external/images/unit7/PRAC-EXER-mozart-allegro-DIAGRAM-KEY.svg" role="img" className="contained" /></div>
<div className="para" id="BinaryAndTernaryPracticeExercises-3-3-2-2">Two-Reprise Continuous Ternary, if looking at the proportion, or Two-Reprise Continuous Rounded Binary, if you interpret the first two notes in bar 13 as being built from the first two notes in bar 1—and if you are considering that Mozart, as a Classical-era composer, is likely to compose a rounded binary. Two-Reprise Continuous Balanced Binary is a label that describes that the endings of the halves are the same, but doesn’t take into account the return of the opening material in bar 21.<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-3-3-2-2" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div>
<div className="autopermalink" data-description="Answer 24.9.4.1"><a href="#BinaryAndTernaryPracticeExercises-3-3-2" title="Copy heading and permalink for Answer 24.9.4.1" aria-label="Copy heading and permalink for Answer 24.9.4.1">🔗</a></div>
</div></details></div>
<div className="autopermalink" data-description="Exercise 24.9.4"><a href="#BinaryAndTernaryPracticeExercises-3-3" title="Copy heading and permalink for Exercise 24.9.4" aria-label="Copy heading and permalink for Exercise 24.9.4">🔗</a></div></article>
</div>
<div className="autopermalink" data-description="Exercise Group 24.9.3–4"><a href="#BinaryAndTernaryPracticeExercises-3" title="Copy heading and permalink for Exercise Group 24.9.3–4" aria-label="Copy heading and permalink for Exercise Group 24.9.3–4">🔗</a></div>
</div>
<div className="exercisegroup" id="BinaryAndTernaryPracticeExercises-4">
<h3 className="heading"><span className="title">Exercise Group.</span></h3>
<div className="introduction" id="BinaryAndTernaryPracticeExercises-4-1"><div className="para" id="BinaryAndTernaryPracticeExercises-4-1-1">Day Three<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-4-1-1" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div></div>
<div className="exercisegroup-exercises">
<article className="exercise exercise-like" id="BinaryAndTernaryPracticeExercises-4-2"><h4 className="heading"><span className="codenumber">5<span className="period heading-divison-mark heading-divison-mark__period">.</span></span></h4>
<div className="para" id="BinaryAndTernaryPracticeExercises-4-2-1-1">Please fill in the blanks below the staves and diagram the form of “After the Ball” from Alexander Gretchaninoff’s <span className="booktitle">Children’s Book</span>, Op.98. Also, name the form.<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-4-2-1-1" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div>  <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-gretchaninoff-A.svg" role="img" className="contained" alt="" /></div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-gretchaninoff-B.svg" role="img" className="contained" alt="" /></div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-gretchaninoff-C.svg" role="img" className="contained" alt="" /></div> <div className="video-box">
<div onclick="this.nextElementSibling.style.display='block'; this.style.display='none'"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 14 96 68" preserveAspectRatio="none"><path fill="#e62117" d="M94.98,28.84c0,0-0.94-6.6-3.81-9.5c-3.64-3.81-7.72-3.83-9.59-4.05c-13.4-0.97-33.52-0.85-33.52-0.85s-20.12-0.12-33.52,0.85c-1.87,0.22-5.95,0.24-9.59,4.05c-2.87,2.9-3.81,9.5-3.81,9.5S0.18,36.58,0,44.33v7.26c0.18,7.75,1.14,15.49,1.14,15.49s0.93,6.6,3.81,9.5c3.64,3.81,8.43,3.69,10.56,4.09c7.53,0.72,31.7,0.89,32.54,0.9c0.01,0,20.14,0.03,33.54-0.94c1.87-0.22,5.95-0.24,9.59-4.05c2.87-2.9,3.81-9.5,3.81-9.5s0.96-7.75,1.02-15.49v-7.26C95.94,36.58,94.98,28.84,94.98,28.84z M38.28,61.41v-27l25.74,13.5L38.28,61.41z"></path></svg></div>
<div className="hidden-content"><iframe className="video" allowfullscreen="" src="https://www.youtube-nocookie.com/embed/3AeFVFC1zy0?&amp;modestbranding=1&amp;rel=0&amp;start=0&amp;end=54" id="BinaryAndTernaryPracticeExercises-4-2-1-6"></iframe></div>
</div> <figure className="figure figure-like" id="BinaryAndTernaryPracticeExercises-4-2-1-7"><figcaption><span className="type">Figure</span><span className="space heading-divison-mark heading-divison-mark__space"> </span><span className="codenumber">24.9.5<span className="period heading-divison-mark heading-divison-mark__period">.</span></span><span className="space heading-divison-mark heading-divison-mark__space"> </span>Gretchaninoff, <span className="booktitle">Children’s Book</span>, Op.98, No. 13, “After the Ball”<div className="autopermalink" data-description="Figure 24.9.5"><a href="#BinaryAndTernaryPracticeExercises-4-2-1-7" title="Copy heading and permalink for Figure 24.9.5" aria-label="Copy heading and permalink for Figure 24.9.5">🔗</a></div></figcaption></figure> <div className="para" id="BinaryAndTernaryPracticeExercises-4-2-1-8">On scratch paper, create a diagram of the form. Include section labels using uppercase letters, phrase labels using lowercase letters, and cadences using the abbreviations PAC, IAC, HC, DC, PC.<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-4-2-1-8" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div> <div className="para" id="BinaryAndTernaryPracticeExercises-4-2-1-9">Circle all of the terms that apply to the name of the form:<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-4-2-1-9" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div> <div className="image-box"><img src="/theory/external/images/unit7/PRAC-EXER-bin-tern-terms-to-circle.svg" role="img" className="contained" /></div>
<div className="solutions"><details id="BinaryAndTernaryPracticeExercises-4-2-2" className="answer solution-like born-hidden-knowl"><summary className="knowl__link"><span className="type">Answer</span><span className="period heading-divison-mark heading-divison-mark__period">.</span></summary><div className="answer solution-like knowl__content">
<div className="image-box"><img src="/theory/external/images/unit7/PRAC-EXER-Gretchaninoff-DIAGRAM-KEY.svg" role="img" className="contained" /></div>
<div className="para" id="BinaryAndTernaryPracticeExercises-4-2-2-2">Sectional Ternary<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-4-2-2-2" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div>
<div className="autopermalink" data-description="Answer 24.9.5.1"><a href="#BinaryAndTernaryPracticeExercises-4-2-2" title="Copy heading and permalink for Answer 24.9.5.1" aria-label="Copy heading and permalink for Answer 24.9.5.1">🔗</a></div>
</div></details></div>
<div className="autopermalink" data-description="Exercise 24.9.5"><a href="#BinaryAndTernaryPracticeExercises-4-2" title="Copy heading and permalink for Exercise 24.9.5" aria-label="Copy heading and permalink for Exercise 24.9.5">🔗</a></div></article><article className="exercise exercise-like" id="BinaryAndTernaryPracticeExercises-4-3"><h4 className="heading"><span className="codenumber">6<span className="period heading-divison-mark heading-divison-mark__period">.</span></span></h4>
<div className="para" id="BinaryAndTernaryPracticeExercises-4-3-1-1">For the theme from Brahms’s <span className="booktitle">Variations on a Theme of Haydn</span> Op. 56a (the theme is also known as “St. Anthony’s Chorale”), please fill in the blanks below the staves and diagram the form. Also, name the form.<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-4-3-1-1" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Brahms-Haydn-A.svg" role="img" className="contained" alt="" /></div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Brahms-Haydn-B.svg" role="img" className="contained" alt="" /></div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Brahms-Haydn-C.svg" role="img" className="contained" alt="" /></div> <div className="image-box"><img src="/theory/external/images/unit7/HW-bin-tern-Brahms-Haydn-D.svg" role="img" className="contained" alt="" /></div> <div className="video-box">
<div onclick="this.nextElementSibling.style.display='block'; this.style.display='none'"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 14 96 68" preserveAspectRatio="none"><path fill="#e62117" d="M94.98,28.84c0,0-0.94-6.6-3.81-9.5c-3.64-3.81-7.72-3.83-9.59-4.05c-13.4-0.97-33.52-0.85-33.52-0.85s-20.12-0.12-33.52,0.85c-1.87,0.22-5.95,0.24-9.59,4.05c-2.87,2.9-3.81,9.5-3.81,9.5S0.18,36.58,0,44.33v7.26c0.18,7.75,1.14,15.49,1.14,15.49s0.93,6.6,3.81,9.5c3.64,3.81,8.43,3.69,10.56,4.09c7.53,0.72,31.7,0.89,32.54,0.9c0.01,0,20.14,0.03,33.54-0.94c1.87-0.22,5.95-0.24,9.59-4.05c2.87-2.9,3.81-9.5,3.81-9.5s0.96-7.75,1.02-15.49v-7.26C95.94,36.58,94.98,28.84,94.98,28.84z M38.28,61.41v-27l25.74,13.5L38.28,61.41z"></path></svg></div>
<div className="hidden-content"><iframe className="video" allowfullscreen="" src="https://www.youtube-nocookie.com/embed/3EbkqX94ng8?&amp;modestbranding=1&amp;rel=0&amp;start=2&amp;end=128" id="BinaryAndTernaryPracticeExercises-4-3-1-6"></iframe></div>
</div> <figure className="figure figure-like" id="BinaryAndTernaryPracticeExercises-4-3-1-7"><figcaption><span className="type">Figure</span><span className="space heading-divison-mark heading-divison-mark__space"> </span><span className="codenumber">24.9.6<span className="period heading-divison-mark heading-divison-mark__period">.</span></span><span className="space heading-divison-mark heading-divison-mark__space"> </span>Brahms, <span className="booktitle">Variations on a Theme of Haydn</span>, Op. 56a<div className="autopermalink" data-description="Figure 24.9.6"><a href="#BinaryAndTernaryPracticeExercises-4-3-1-7" title="Copy heading and permalink for Figure 24.9.6" aria-label="Copy heading and permalink for Figure 24.9.6">🔗</a></div></figcaption></figure> <div className="para" id="BinaryAndTernaryPracticeExercises-4-3-1-8">On scratch paper, create a diagram of the form. Include section labels using uppercase letters, phrase labels using lowercase letters, and cadences using the abbreviations PAC, IAC, HC, DC, PC.<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-4-3-1-8" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div> <div className="para" id="BinaryAndTernaryPracticeExercises-4-3-1-9">Circle all of the terms that apply to the name of the form:<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-4-3-1-9" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div> <div className="image-box"><img src="/theory/external/images/unit7/PRAC-EXER-bin-tern-terms-to-circle.svg" role="img" className="contained" /></div>
<div className="solutions"><details id="BinaryAndTernaryPracticeExercises-4-3-2" className="answer solution-like born-hidden-knowl"><summary className="knowl__link"><span className="type">Answer</span><span className="period heading-divison-mark heading-divison-mark__period">.</span></summary><div className="answer solution-like knowl__content">
<div className="image-box"><img src="/theory/external/images/unit7/PRAC-EXER-Brahms-Haydn-var-DIAGRAM-KEY.svg" role="img" className="contained" /></div>
<div className="para" id="BinaryAndTernaryPracticeExercises-4-3-2-2">Two-Reprise Sectional Rounded Binary (because the motives from the first section are used in the construction of the melody of the second section)<div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-4-3-2-2" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div>
<div className="autopermalink" data-description="Answer 24.9.6.1"><a href="#BinaryAndTernaryPracticeExercises-4-3-2" title="Copy heading and permalink for Answer 24.9.6.1" aria-label="Copy heading and permalink for Answer 24.9.6.1">🔗</a></div>
</div></details></div>
<div className="autopermalink" data-description="Exercise 24.9.6"><a href="#BinaryAndTernaryPracticeExercises-4-3" title="Copy heading and permalink for Exercise 24.9.6" aria-label="Copy heading and permalink for Exercise 24.9.6">🔗</a></div></article>
</div>
<div className="autopermalink" data-description="Exercise Group 24.9.5–6"><a href="#BinaryAndTernaryPracticeExercises-4" title="Copy heading and permalink for Exercise Group 24.9.5–6" aria-label="Copy heading and permalink for Exercise Group 24.9.5–6">🔗</a></div>
</div>
<section className="conclusion" id="BinaryAndTernaryPracticeExercises-5"><div className="para" id="BinaryAndTernaryPracticeExercises-5-1">Click <a className="external" href="http://musictheory.pugetsound.edu/hw/MT21C_HW_33.pdf" target="_blank">here to download the first homework assignment for this chapter.</a><div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-5-1" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div>
<div className="para" id="BinaryAndTernaryPracticeExercises-5-2">Click <a className="external" href="http://musictheory.pugetsound.edu/hw/MT21C_HW_34.pdf" target="_blank">here to download the second homework assignment for this chapter.</a><div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-5-2" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div>
<div className="para" id="BinaryAndTernaryPracticeExercises-5-3">Click <a className="external" href="http://musictheory.pugetsound.edu/hw/MT21C_HW_35.pdf" target="_blank">here to download the third homework assignment for this chapter.</a><div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-5-3" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div>
<div className="para" id="BinaryAndTernaryPracticeExercises-5-4">Click <a className="external" href="http://musictheory.pugetsound.edu/hw/MT21C_HW_32.pdf" target="_blank">here to download the review sheet for material studied prior to this chapter.</a><div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-5-4" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div>
<div className="para" id="BinaryAndTernaryPracticeExercises-5-5">PDF versions of the textbook, homework exercises, and practice exercises can be found at <a className="external" href="http://musictheory.pugetsound.edu" target="_blank"><code className="code-inline tex2jax_ignore">musictheory.pugetsound.edu</code></a><div className="autopermalink" data-description="Paragraph"><a href="#BinaryAndTernaryPracticeExercises-5-5" title="Copy heading and permalink for Paragraph" aria-label="Copy heading and permalink for Paragraph">🔗</a></div>
</div></section><div className="autopermalink" data-description="Exercises 24.9: Practice Exercises"><a href="#BinaryAndTernaryPracticeExercises" title="Copy heading and permalink for Exercises 24.9: Practice Exercises" aria-label="Copy heading and permalink for Exercises 24.9: Practice Exercises">🔗</a></div></section></div>
<div id="ptx-content-footer" className="ptx-content-footer">
</div>` }} />
      </div>

      {/* Back to Theory Index */}
      <div className="mt-10 pt-6 border-t border-gray-200 dark:border-gray-700">
        <Link
          to="/theory"
          className="inline-flex items-center gap-2 px-4 py-2 bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 text-gray-700 dark:text-gray-200 rounded-lg transition-colors"
        >
          ← Back to Theory Index
        </Link>
      </div>
    </article>
  );
};

export default Ch24BinaryandternarypracticeexercisesPage;
