import re
import json
from pathlib import Path

# Paths
BASE_DIR = Path("/Users/antonyleedale/GIT OLD WEBSITE IGCSE/igcse-music-study-hub")
HTML_FILE = BASE_DIR / "NEW WEBSITE/glossary-full.html"
OUTPUT_FILE = BASE_DIR / "services/glossaryData.ts"

def main():
    print(f"📖 Reading {HTML_FILE}")
    with open(HTML_FILE, "r", encoding="utf-8", errors="replace") as f:
        content = f.read()

    # Regex to find rows with 3 cells (Index, Term, Definition)
    # The term cell has colspan=2 usually
    # Structure:
    # <tr>
    #   <td>...<b>123</b>...</td>
    #   <td colspan=2>...<b>Term</b>...</td>
    #   <td>...Definition...</td>
    # </tr>
    
    # We'll use a fairly loose regex to capture row constraints
    row_pattern = re.compile(r"<tr>(.*?)</tr>", re.DOTALL)
    cell_pattern = re.compile(r"<td[^>]*>(.*?)</td>", re.DOTALL)
    
    terms = []
    
    for row_match in row_pattern.finditer(content):
        row_html = row_match.group(1)
        cells = cell_pattern.findall(row_html)
        
        if len(cells) >= 3:
            # Extract Index
            idx_match = re.search(r"<b>\s*(\d+)\s*</b>", cells[0])
            if not idx_match:
                continue
                
            index = int(idx_match.group(1))
            
            # Extract Term
            # Remove tags and whitespace
            raw_term = re.sub(r"<[^>]+>", "", cells[1]).strip()
            term = raw_term.replace("&quot;", '"').replace("&amp;", "&")
            
            # Extract Definition
            raw_def = re.sub(r"<[^>]+>", "", cells[2]).strip()
            definition = raw_def.replace("&quot;", '"').replace("&amp;", "&")
            
            if term and definition:
                terms.append({
                    "id": index,
                    "term": term,
                    "definition": definition
                })

    print(f"✅ Extracted {len(terms)} terms.")
    
    # Sort by term name alpha just in case, though index order is fine
    # terms.sort(key=lambda x: x['term'].lower())

    # Generate TypeScript file
    ts_content = f"""// Generated by scripts/convert_glossary.py
// Total terms: {len(terms)}

export interface GlossaryTerm {{
  id: number;
  term: string;
  definition: string;
  category?: string; // Optional category if we want to add later
}}

export const glossaryTerms: GlossaryTerm[] = {json.dumps(terms, indent=2)};
"""

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(ts_content)
        
    print(f"💾 Saved to {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
